apiVersion: apps/v1
kind: Deployment
metadata:
  name: aichat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aichat
  template:
    metadata:
      labels:
        app: aichat
    spec:
      containers:
        - name: aichat-container
          image: ghcr.io/notbjoggisatall/aichat:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      imagePullSecrets:
      - name: credentials
---
apiVersion: v1
kind: Service
metadata:
  name: aichat-service
spec:
  selector:
    app: aichat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
